"""Inbound office-document parsing through local anydoc (firecrawl-anydoc)."""

from app.services.document_parser.errors import (
    DocumentParseError,
    DocumentParseTimeoutError,
    DocumentParseUnavailableError,
    DocumentTooLargeError,
    EncryptedDocumentError,
    MalformedDocumentError,
    MissingDocumentPartError,
    ResourceLimitedDocumentError,
    UnsupportedDocumentError,
)
from app.services.document_parser.runtime import (
    MAX_CONCURRENCY,
    TIMEOUT_SECONDS,
    convert_document_isolated,
    convert_document_isolated_async,
)
from app.services.document_parser.service import (
    MAX_INPUT_BYTES,
    MAX_OUTPUT_CHARS,
    OFFICE_EXTENSIONS,
    TEXT_EXTENSIONS,
    convert_document,
    convert_document_path,
    decode_text_bytes,
    extract_document_text,
    format_parse_failure,
    is_plain_text_document,
    needs_extraction,
    normalize_markdown,
    save_extracted_markdown,
    unsupported_read_document_message,
)

__all__ = [
    "MAX_CONCURRENCY",
    "MAX_INPUT_BYTES",
    "MAX_OUTPUT_CHARS",
    "OFFICE_EXTENSIONS",
    "TEXT_EXTENSIONS",
    "TIMEOUT_SECONDS",
    "DocumentParseError",
    "DocumentParseTimeoutError",
    "DocumentParseUnavailableError",
    "DocumentTooLargeError",
    "EncryptedDocumentError",
    "MalformedDocumentError",
    "MissingDocumentPartError",
    "ResourceLimitedDocumentError",
    "UnsupportedDocumentError",
    "convert_document",
    "convert_document_isolated",
    "convert_document_isolated_async",
    "convert_document_path",
    "decode_text_bytes",
    "extract_document_text",
    "format_parse_failure",
    "is_plain_text_document",
    "needs_extraction",
    "normalize_markdown",
    "save_extracted_markdown",
    "unsupported_read_document_message",
]
