"""Seed rows extracted from builtin.py. Data only."""

from typing import Any

FEISHU_SEED_TOOLS: list[dict[str, Any]] = [
        {
            "name": "send_feishu_message",
            "display_name": "Feishu Message",
            "description": "Send a message to a human colleague via Feishu. Can only message people in your relationships.",
            "category": "feishu",
            "icon": "💬",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "member_name": {"type": "string", "description": "Recipient name"},
                    "message": {"type": "string", "description": "Message content"},
                },
                "required": ["member_name", "message"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_user_search",
            "display_name": "Feishu User Search",
            "description": "Search for a colleague in the Feishu (Lark) directory by name. Returns their open_id, email, and department.",
            "category": "feishu",
            "icon": "🔍",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "The colleague's name to search for"},
                },
                "required": ["name"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "bitable_create_app",
            "display_name": "Bitable Create",
            "description": "Create a Feishu Bitable app in Feishu Drive. Returns a direct link and App Token. Next, use bitable_list_tables to view the initial tables.",
            "category": "feishu",
            "icon": "📊",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "Name of the new Bitable, for example 「项目追踪表」."},
                    "folder_token": {
                        "type": "string",
                        "description": "Optional parent folder_token. Defaults to the root of 「我的空间」.",
                    },
                },
                "required": ["name"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "bitable_list_tables",
            "display_name": "Bitable List Tables",
            "description": "List all tables in a Feishu Bitable. url supports Bitable and Wiki links. Use this tool to identify the tables in the requested Bitable.",
            "category": "feishu",
            "icon": "📊",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The Bitable URL."},
                },
                "required": ["url"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "bitable_list_fields",
            "display_name": "Bitable List Fields",
            "description": "List all fields in a specified Feishu Bitable table. url supports Bitable and Wiki links. You must call this tool before querying or modifying data to learn the field names and types.",
            "category": "feishu",
            "icon": "⌨️",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The Bitable URL."},
                    "table_id": {"type": "string", "description": "The specific table ID. Optional when url includes tbl."},
                },
                "required": ["url"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "bitable_query_records",
            "display_name": "Bitable Query Records",
            "description": "Query rows in a Feishu Bitable. An optional filter can be provided.",
            "category": "feishu",
            "icon": "🔍",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The Bitable URL."},
                    "table_id": {"type": "string", "description": "The specific table ID. Optional when url includes tbl."},
                    "filter_info": {
                        "type": "string",
                        "description": "Optional FQL filter, for example 'CurrentValue.[Status]=\"Done\"'. If you are unsure of the filter syntax, omit this and filter all returned data locally.",
                    },
                    "max_results": {
                        "type": "integer",
                        "description": "Maximum number of records to return (default: 100).",
                    },
                },
                "required": ["url"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "bitable_create_record",
            "display_name": "Bitable Create Record",
            "description": "Create a row in a Feishu Bitable. fields is a dictionary whose keys are field names (obtain them with bitable_list_fields first) and values are the corresponding values.",
            "category": "feishu",
            "icon": "+",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The Bitable URL."},
                    "table_id": {"type": "string", "description": "The specific table ID. Optional when url includes tbl."},
                    "fields": {
                        "type": "string",
                        "description": 'A JSON string representing the fields to insert. Example: \'{"Name": "张三", "Age": 30}\'',
                    },
                },
                "required": ["url", "fields"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "bitable_update_record",
            "display_name": "Bitable Update Record",
            "description": "Update a specified row in a Feishu Bitable.",
            "category": "feishu",
            "icon": "✏️",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The Bitable URL."},
                    "table_id": {"type": "string", "description": "The specific table ID. Optional when url includes tbl."},
                    "record_id": {
                        "type": "string",
                        "description": "The record_id to update, obtained with bitable_query_records.",
                    },
                    "fields": {
                        "type": "string",
                        "description": 'A JSON string representing the fields to update. Example: \'{"Status": "Done"}\'',
                    },
                },
                "required": ["url", "record_id", "fields"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "bitable_delete_record",
            "display_name": "Bitable Delete Record",
            "description": "Delete a specified row from a Feishu Bitable.",
            "category": "feishu",
            "icon": "🗑️",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The Bitable URL."},
                    "table_id": {"type": "string", "description": "The specific table ID. Optional when url includes tbl."},
                    "record_id": {
                        "type": "string",
                        "description": "The record_id to delete, obtained with bitable_query_records.",
                    },
                },
                "required": ["url", "record_id"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_doc_search",
            "display_name": "Feishu Doc Search",
            "description": "Search Feishu cloud documents by keyword using the official document search API. Useful when a wiki or knowledge base has too many files to browse manually.",
            "category": "feishu",
            "icon": "🔎",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Search keyword, e.g. '恩菲' or '客户周报'"},
                    "docs_types": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": ["doc", "docx", "sheet", "bitable", "file", "folder", "mindnote", "slides"],
                        },
                        "description": "Optional file type filter.",
                    },
                    "count": {"type": "integer", "description": "Number of results to return (default 10, max 50)."},
                    "offset": {"type": "integer", "description": "Result offset for pagination (default 0)."},
                },
                "required": ["query"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_doc_read",
            "display_name": "Feishu Doc Read",
            "description": "Read the text content of a Feishu document (Docx). Provide the document token from its URL.",
            "category": "feishu",
            "icon": "📄",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "document_token": {"type": "string", "description": "Feishu document token (from document URL)"},
                    "max_chars": {"type": "integer", "description": "Max characters to return (default 6000, max 20000)"},
                },
                "required": ["document_token"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_doc_create",
            "display_name": "Feishu Doc Create",
            "description": "Create a new Feishu document with a given title. Returns the new document token and URL.",
            "category": "feishu",
            "icon": "📝",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "title": {"type": "string", "description": "Document title"},
                    "folder_token": {"type": "string", "description": "Optional: parent folder token"},
                },
                "required": ["title"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_doc_append",
            "display_name": "Feishu Doc Append",
            "description": "Append text content to an existing Feishu document as new paragraphs at the end.",
            "category": "feishu",
            "icon": "📎",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "document_token": {"type": "string", "description": "Feishu document token"},
                    "content": {"type": "string", "description": "Text content to append"},
                },
                "required": ["document_token", "content"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_drive_share",
            "display_name": "Feishu Drive Share",
            "description": "Manage collaborators for any Feishu Drive file (docx, bitable, sheet, etc.). Add, remove, or list collaborators with view/edit/full_access permissions.",
            "category": "feishu",
            "icon": "🔗",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "document_token": {"type": "string", "description": "File token (from URL or previous tool output)"},
                    "doc_type": {
                        "type": "string",
                        "enum": ["docx", "bitable", "sheet", "doc", "folder", "mindnote", "slides"],
                        "description": "File type. Default: 'docx'",
                    },
                    "action": {
                        "type": "string",
                        "enum": ["add", "remove", "list"],
                        "description": "'add' to grant, 'remove' to revoke, 'list' to view",
                    },
                    "member_names": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Colleague names to add/remove (auto-searched)",
                    },
                    "member_open_ids": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Feishu open_ids directly",
                    },
                    "permission": {
                        "type": "string",
                        "enum": ["view", "edit", "full_access"],
                        "description": "Permission level. Default: 'edit'",
                    },
                },
                "required": ["document_token", "action"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_drive_delete",
            "display_name": "Feishu Drive Delete",
            "description": "Delete a file or folder from Feishu Drive. The file is moved to the recycle bin. Supports all file types: docx, bitable, sheet, folder, etc.",
            "category": "feishu",
            "icon": "🗑️",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "file_token": {"type": "string", "description": "Token of the file to delete"},
                    "file_type": {
                        "type": "string",
                        "enum": ["file", "docx", "bitable", "folder", "doc", "sheet", "mindnote", "shortcut", "slides"],
                        "description": "Type of the file to delete",
                    },
                },
                "required": ["file_token", "file_type"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_calendar_list",
            "display_name": "Feishu Calendar List",
            "description": "List Feishu calendar events. No email or authorization needed.",
            "category": "feishu",
            "icon": "📅",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "start_time": {"type": "string", "description": "Range start, ISO 8601. Default: now."},
                    "end_time": {"type": "string", "description": "Range end, ISO 8601. Default: 7 days from now."},
                    "max_results": {"type": "integer", "description": "Max events to return (default 20)"},
                },
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_calendar_create",
            "display_name": "Feishu Calendar Create",
            "description": "Create a Feishu calendar event. Supports inviting colleagues by name. No email needed.",
            "category": "feishu",
            "icon": "📅",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "summary": {"type": "string", "description": "Event title"},
                    "start_time": {"type": "string", "description": "Event start in ISO 8601 with timezone"},
                    "end_time": {"type": "string", "description": "Event end in ISO 8601 with timezone"},
                    "description": {"type": "string", "description": "Event description or agenda"},
                    "attendee_names": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Names of colleagues to invite",
                    },
                    "location": {"type": "string", "description": "Event location"},
                },
                "required": ["summary", "start_time", "end_time"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_calendar_update",
            "display_name": "Feishu Calendar Update",
            "description": "Update an existing Feishu calendar event. Provide only the fields you want to change.",
            "category": "feishu",
            "icon": "📅",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "user_email": {"type": "string", "description": "Calendar owner's email"},
                    "event_id": {"type": "string", "description": "Event ID from feishu_calendar_list"},
                    "summary": {"type": "string", "description": "New title"},
                    "start_time": {"type": "string", "description": "New start time (ISO 8601)"},
                    "end_time": {"type": "string", "description": "New end time (ISO 8601)"},
                },
                "required": ["user_email", "event_id"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_calendar_delete",
            "display_name": "Feishu Calendar Delete",
            "description": "Delete (cancel) a Feishu calendar event.",
            "category": "feishu",
            "icon": "🗑️",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "user_email": {"type": "string", "description": "Calendar owner's email"},
                    "event_id": {"type": "string", "description": "Event ID to delete"},
                },
                "required": ["user_email", "event_id"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_approval_create",
            "display_name": "Feishu Approval Create",
            "description": "Start a Feishu approval workflow instance. You must know the approval definition's approval_code and the content for its form fields.",
            "category": "feishu",
            "icon": "📝",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "approval_code": {
                        "type": "string",
                        "description": "The approval definition's unique code (approval_code).",
                    },
                    "user_id": {
                        "type": "string",
                        "description": "The initiator's open_id. Obtain it with feishu_user_search.",
                    },
                    "form_data": {
                        "type": "string",
                        "description": 'A JSON string containing the form data, for example \'[{"id":"widget1","type":"input","value":"这是内容"}]\'',
                    },
                },
                "required": ["approval_code", "user_id", "form_data"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_approval_query",
            "display_name": "Feishu Approval Query",
            "description": "Query a list of specified Feishu approval instances. Supports filtering by status (PENDING, APPROVED, REJECTED, CANCELED, DELETED).",
            "category": "feishu",
            "icon": "📋",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "approval_code": {
                        "type": "string",
                        "description": "The approval definition's unique code (approval_code).",
                    },
                    "status": {
                        "type": "string",
                        "description": "Optional status filter: PENDING, APPROVED, REJECTED, CANCELED, DELETED.",
                    },
                },
                "required": ["approval_code"],
            },
            "config": {},
            "config_schema": {},
        },
        {
            "name": "feishu_approval_get",
            "display_name": "Feishu Approval Get",
            "description": "Get detailed information and the current approval status for a specified Feishu approval instance.",
            "category": "feishu",
            "icon": "📊",
            "is_default": False,
            "parameters_schema": {
                "type": "object",
                "properties": {
                    "instance_id": {"type": "string", "description": "The approval instance's instance_id."},
                },
                "required": ["instance_id"],
            },
            "config": {},
            "config_schema": {},
        },
]
